# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nazwa')),
                ('description', models.TextField(verbose_name='opis')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'karta',
                'verbose_name_plural': 'karty',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa')),
                ('description', models.TextField(verbose_name='opis')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preparation_time', models.IntegerField(help_text='w minutach')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'danie',
                'verbose_name_plural': 'dania',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='emenu.Dish'),
        ),
    ]
