# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'dishes/', verbose_name='zdj\u0119cie'),
        ),
    ]
