# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emenu', '0002_dish_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emenu.Card'),
        ),
    ]
