# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emenu', '0005_auto_20161206_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='emenu.Card'),
        ),
    ]
